<script lang="ts">
	import '../lib/app.css';
	import favicon from '$lib/assets/favicon.svg';
	import Navbar from '$lib/components/Navbar.svelte';
	// LayoutProps is generated by SvelteKit from +layout.server.ts's load return.
	import type { LayoutProps } from './$types';

	let { children, data }: LayoutProps = $props();
</script>

<svelte:head><link rel="icon" href={favicon} /></svelte:head>

<Navbar user={data.user} />
<main class="mx-auto max-w-5xl px-4 py-8">
	{@render children()}
</main>
